apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  destination:
    namespace: development
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      releaseName: guestbook
    path: kubernetes
    repoURL: git@github.com:argoproj/argocd-example-apps.git
    targetRevision: main
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - Replace=false
    - Prune=false
    - preserveResourceOnDeletion=true